[phases.setup]
nixPkgs = ["php", "phpExtensions.gd", "composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan storage:link || true"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"